### ISSUE TITLE
Yarn v2 issue with @types

### ISSUE THREAD

**Issue by vhiairrassary** [arcanis/pnp-webpack-plugin#14]
I am testing `pnp-webpack-plugin` with yarn v2 (2.0.0-rc.1, but same output with 2.0.0-rc.6).

It works well with JS: https://github.com/vhiairrassary/test-yarn-v2.

When I want to use typescript, I can't use `@types` packages. The code now is https://github.com/vhiairrassary/test-yarn-v2/compare/ts?expand=1.

- Without adding `@types/express`, I get the following error, which is normal
```
ERROR in [...]/test-yarn-v2/packages/a/sources/index.ts
./sources/index.ts
[tsl] ERROR in [...]/test-yarn-v2/packages/a/sources/index.ts(1,26)
      TS7016: Could not find a declaration file for module 'express'. '[...]/test-yarn-v2/.yarn/cache/express-npm-4.17.1-e3afcd926c.zip/node_modules/express/index.js' implicitly has an 'any' type.
```

- Adding to the package using `yarn workspace @mytest/a add @types/express` results in the same error as above, but here it should work out of the box.

- Adding to the **root** package using `yarn workspace @mytest/root add @types/express`:
```
ERROR in [...]/test-yarn-v2/packages/a/sources/index.ts
./sources/index.ts
[tsl] ERROR in [...]/test-yarn-v2/packages/a/sources/index.ts(6,67)
      TS2339: Property 'send' does not exist on type 'Response'.
```
Which is really weird as send is part of Response.

Am I missing something?

**Comment by arcanis** [comment]
For the second one I remember seeing that before, but I haven't got time to investigate yet 🤔

For the third one, that looks weird as well but at least the types definition are found. My best guess would be that the version of `@types/express-serve-static-core` that got install doesn't list `send` (since `@types/express` depends on it through `*`, technically any version would match - including those without `send`).

**Comment by vhiairrassary** [comment]
Weird, with `unzip -c .yarn/cache/@types-express-serve-static-core-npm-4.16.9-56b6aa787f.zip node_modules/@types/express-serve-static-core/index.d.ts` I can see :
```
export interface Response extends http.ServerResponse, Express.Response {
    /**
     * Set status `code`.
     */
    status(code: number): Response;

    /**
     * Set the response HTTP status code to `statusCode` and send its string representation as the response body.
     * @link http://expressjs.com/4x/api.html#res.sendStatus
     *
     * Examples:
     *
     *    res.sendStatus(200); // equivalent to res.status(200).send('OK')
     *    res.sendStatus(403); // equivalent to res.status(403).send('Forbidden')
     *    res.sendStatus(404); // equivalent to res.status(404).send('Not Found')
     *    res.sendStatus(500); // equivalent to res.status(500).send('Internal Server Error')
     */
    sendStatus(code: number): Response;

    /**
     * Set Link header field with the given `links`.
     *
     * Examples:
     *
     *    res.links({
     *      next: 'http://api.example.com/users?page=2',
     *      last: 'http://api.example.com/users?page=5'
     *    });
     */
    links(links: any): Response;

    /**
     * Send a response.
     *
     * Examples:
     *
     *     res.send(new Buffer('wahoo'));
     *     res.send({ some: 'json' });
     *     res.send('<p>some html</p>');
     *     res.status(404).send('Sorry, cant find that');
     */
    send: Send;
```
4.16.9 is actually the latest version listed on npm: https://www.npmjs.com/package/@types/express-serve-static-core

**Comment by vhiairrassary** [comment]
For the second one, with `PNP_DEBUG_LEVEL=5` we can see `@types/express` is required by `@mytest/root@workspace:.` which is not the correct package:
```
{
  fn: 'resolveToUnqualified',
  args: [
    '@types/express',
    '[...]/test-yarn-v2/',
    { considerBuiltins: false }
  ],
  error: Error: A package is trying to access another package without the second one being listed as a dependency of the first one
  
  Required package: @types/express (via "@types/express")
  Required by: @mytest/root@workspace:. (via [...]/test-yarn-v2/)
  
      at Object.makeError ([...]/test-yarn-v2/.pnp.js:6841:26)
      at resolveToUnqualified ([...]/test-yarn-v2/.pnp.js:9248:43)
      at [...]/test-yarn-v2/.pnp.js:9323:32
      at Object.resolveToUnqualified ([...]/test-yarn-v2/.pnp.js:8937:50)
      at resolveModuleName ([...]/test-yarn-v2/.yarn/virtual/ts-pnp-virtual-11ad59ec2c/0/cache/ts-pnp-npm-1.1.4-68c6fd0fd3.zip/node_modules/ts-pnp/index.js:22:25)
      at [...]/test-yarn-v2/.yarn/virtual/ts-loader-virtual-081796e733/0/cache/ts-loader-npm-6.1.2-234ca82b1e.zip/node_modules/ts-loader/dist/servicesHost.js:412:44
      at resolveModule ([...]/test-yarn-v2/.yarn/virtual/ts-loader-virtual-081796e733/0/cache/ts-loader-npm-6.1.2-234ca82b1e.zip/node_modules/ts-loader/dist/servicesHost.js:391:26)
      at [...]/test-yarn-v2/.yarn/virtual/ts-loader-virtual-081796e733/0/cache/ts-loader-npm-6.1.2-234ca82b1e.zip/node_modules/ts-loader/dist/servicesHost.js:98:63
      at Array.map (<anonymous>)
      at Object.resolveModuleNames ([...]/test-yarn-v2/.yarn/virtual/ts-loader-virtual-081796e733/0/cache/ts-loader-npm-6.1.2-234ca82b1e.zip/node_modules/ts-loader/dist/servicesHost.js:98:45)
      at Object.compilerHost.resolveModuleNames ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:125749:52)
      at resolveModuleNamesWorker ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:91510:127)
      at resolveModuleNamesReusingOldState ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:91756:24)
      at processImportedModules ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:93095:35)
      at findSourceFile ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:92896:17)
      at [...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:92742:85
      at getSourceFileFromReferenceWorker ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:92709:34)
      at processSourceFile ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:92742:13)
      at processRootFile ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:92572:13)
      at [...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:91588:60
      at Object.forEach ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:288:30)
      at Object.createProgram ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:91588:16)
      at synchronizeHostData ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:125769:26)
      at Object.getProgram ([...]/test-yarn-v2/.yarn/cache/typescript-npm-3.6.3-77c6d05fb2.zip/node_modules/typescript/lib/typescript.js:125861:13)
      at successfulTypeScriptInstance ([...]/test-yarn-v2/.yarn/virtual/ts-loader-virtual-081796e733/0/cache/ts-loader-npm-6.1.2-234ca82b1e.zip/node_modules/ts-loader/dist/instances.js:179:80)
      at Object.getTypeScriptInstance ([...]/test-yarn-v2/.yarn/virtual/ts-loader-virtual-081796e733/0/cache/ts-loader-npm-6.1.2-234ca82b1e.zip/node_modules/ts-loader/dist/instances.js:34:12)
      at Object.loader ([...]/test-yarn-v2/.yarn/virtual/ts-loader-virtual-081796e733/0/cache/ts-loader-npm-6.1.2-234ca82b1e.zip/node_modules/ts-loader/dist/index.js:17:41)
      at LOADER_EXECUTION ([...]/test-yarn-v2/.yarn/cache/loader-runner-npm-2.4.0-1dda35a78d.zip/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
      at runSyncOrAsync ([...]/test-yarn-v2/.yarn/cache/loader-runner-npm-2.4.0-1dda35a78d.zip/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
      at iterateNormalLoaders ([...]/test-yarn-v2/.yarn/cache/loader-runner-npm-2.4.0-1dda35a78d.zip/node_modules/loader-runner/lib/LoaderRunner.js:232:2) {
    code: 'MODULE_NOT_FOUND',
    pnpCode: 'UNDECLARED_DEPENDENCY',
    data: {
      request: '@types/express',
      issuer: '[...]/test-yarn-v2/',
      issuerLocator: [Object],
      dependencyName: '@types/express',
      candidates: [Array]
    }
  },
  result: null
}
```

**Comment by vhiairrassary** [comment]
I suspect the answer might be in ts-pnp: https://github.com/arcanis/ts-pnp/blob/master/index.js. But I don't know how to monkey patch (as packages are stored as zip files) or debug (`inspect-brk` breaks the debugger with `"NODE_OPTIONS='--require [...]/test-yarn-v2/.pnp.js --inspect --inspect-brk' webpack-cli --progress"`).

Do you know what is the recommended way to debug in such situations?

**Comment by arcanis** [comment]
Two options:

- You can edit directly within the zip archives with Emacs or Vim (too bad VSCode doesn't have this neat feature :().

- You can "unplug" the package you want to edit with `yarn unplug <name>`. It will be stored inside `.yarn/unplugged/<package-name>` and you can edit it at will.

I think you're right btw - looking at [this line](https://github.com/arcanis/ts-pnp/blob/master/index.js#L16), it's clear that the resolution is made from the top-level of the project (which is obtained from `pnp.topLevel`). I'm not 100% sure I remember whether I did it on purpose or if it's a bug 🤔

**Comment by vhiairrassary** [comment]
> Two options:
> 
> * You can edit directly within the zip archives with Emacs or Vim (too bad VSCode doesn't have this neat feature :().
> * You can "unplug" the package you want to edit with `yarn unplug <name>`. It will be stored inside `.yarn/unplugged/<package-name>` and you can edit it at will.
> 

`unplug`: Awesome 🎉

> I think you're right btw - looking at [this line](https://github.com/arcanis/ts-pnp/blob/master/index.js#L16), it's clear that the resolution is made from the top-level of the project (which is obtained from `pnp.topLevel`). I'm not 100% sure I remember whether I did it on purpose or if it's a bug 🤔

I confirm. At https://github.com/arcanis/ts-pnp/blob/master/index.js#L22, Replacing
```js
pnp.resolveToUnqualified(typesPackagePath, `${topLevelLocation}/`, {considerBuiltins: false});
```
by
```js
pnp.resolveToUnqualified(typesPackagePath, issuer, {considerBuiltins: false});
```
fix my issue and the example compiles as expected! But I am not confident in creating a PR for the issue 😅

**Comment by arcanis** [comment]
I vaguely remember that it was because of an oddity with the way the `@types` dependencies depend on one another ... it's a bit fuzzy (I should have wrote a test about it!), but iirc they don't really work if there's multiple times the same `@types` package in the same project with different versions. By only resolving them from the root, we never have this problem.

**Comment by walkerburgin** [comment]
I hit this as well while experimenting a bit with yarn v2 to get a feel for how difficult migration will ultimately be. Unplugging and patching ts-pnp as described here got me unblocked (thank you!).

> Or do we have to manually install the @types/* packages in the project root?

If this turns out to be the case it would be a pretty hard blocker for us being able to adopt v2. We have a pretty massive TypeScript monorepo (hundreds of packages) and rely heavily on each of them declaring their `@types` dev dependencies independently so that we can reason about it.

**Comment by alubbe** [comment]
Just to clarify, my issue can be reproduced by cloning https://github.com/alubbe/yarn2_workspace_typescript and running `yarn install && cd packages/rofl && yarn start`. And all it takes to break it is to go from a simple repo to a monorepo with these simple changes: https://github.com/alubbe/yarn2_workspace_typescript/commit/7839493116b4df41a7dfd328b9819116d20d1cff

**Comment by alubbe** [comment]
I hate to bump my own ticket, but this issue is causing major headaches for us - is there anything we can do to help investigate this further? Is this even the right place to report the issue? Why does TS find all the JS files just fine, but struggle to find a dependency's own type declaration file? Any pointers would be extremely helpful!

**Comment by alubbe** [comment]
Fixed by https://github.com/yarnpkg/berry/issues/1483#issuecomment-663939833
